
project_id = "zjaswhqgqvlqpoosbfqn"

[functions.sync-shopify-products]
verify_jwt = false

[functions.generate-deepseek-images]
verify_jwt = false

[functions.test-deepseek-connection]
verify_jwt = false
