
project_id = "zjaswhqgqvlqpoosbfqn"

[functions.sync-shopify-products]
verify_jwt = false

[functions.generate-fal-images]
verify_jwt = false
import_map = ["https://deno.land/std@0.168.0/http/server.ts"]
allowed_domains = ["api.deepseek.ai"]
