// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjaswhqgqvlqpoosbfqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYXN3aHFncXZscXBvb3NiZnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MzQ0MjAsImV4cCI6MjA1MjUxMDQyMH0.LG4SH9IwPv4NpOxQv_DjMAANhRysIiVyIhpPTCptBrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);